-- NOTE: This file is auto generated by ./sql-generator

-- GoogleDriveRepository.getCredentials
select
  "userId",
  "refreshToken",
  "folderId",
  "connectedAt"
from
  "user_google_drive"
where
  "userId" = $1

-- GoogleDriveRepository.upsertCredentials
insert into
  "user_google_drive" ("userId", "refreshToken")
values
  ($1, $2)
on conflict ("userId") do update
set
  "refreshToken" = $3

-- GoogleDriveRepository.setFolderId
update "user_google_drive"
set
  "folderId" = $1
where
  "userId" = $2

-- GoogleDriveRepository.deleteCredentials
delete from "user_google_drive"
where
  "userId" = $1

-- GoogleDriveRepository.getUploadedAssetIds
select
  "assetId"
from
  "google_drive_upload"
where
  "userId" = $1
  and "assetId" in ($2)

-- GoogleDriveRepository.recordUpload
insert into
  "google_drive_upload" ("userId", "assetId", "driveFileId")
values
  ($1, $2, $3)
on conflict ("userId", "assetId") do update
set
  "driveFileId" = "excluded"."driveFileId"
