-- NOTE: This file is auto generated by ./sql-generator

-- GoogleDriveRepository.getCredentials
select
  "userId",
  "refreshToken",
  "folderId",
  "connectedAt"
from
  "user_google_drive"
where
  "userId" = $1

-- GoogleDriveRepository.upsertCredentials
insert into
  "user_google_drive" ("userId", "refreshToken")
values
  ($1, $2)
on conflict ("userId") do update
set
  "refreshToken" = $3

-- GoogleDriveRepository.setFolderId
update "user_google_drive"
set
  "folderId" = $1
where
  "userId" = $2

-- GoogleDriveRepository.deleteCredentials
delete from "user_google_drive"
where
  "userId" = $1

-- GoogleDriveRepository.streamPendingUploads
select distinct
  "album_user"."userId" as "userId",
  "album_asset"."assetId" as "assetId"
from
  "album_asset"
  inner join "album" on "album"."id" = "album_asset"."albumId"
  inner join "album_user" on "album_user"."albumId" = "album"."id"
  inner join "user_google_drive" on "user_google_drive"."userId" = "album_user"."userId"
  inner join "asset" on "asset"."id" = "album_asset"."assetId"
  left join "google_drive_upload" on "google_drive_upload"."assetId" = "album_asset"."assetId"
  and "google_drive_upload"."userId" = "album_user"."userId"
where
  "album_user"."role" = $1
  and "album"."deletedAt" is null
  and "asset"."deletedAt" is null
  and "google_drive_upload"."assetId" is null

-- GoogleDriveRepository.getUploadedAssetIds
select
  "assetId"
from
  "google_drive_upload"
where
  "userId" = $1
  and "assetId" in ($2)

-- GoogleDriveRepository.recordUpload
insert into
  "google_drive_upload" ("userId", "assetId", "driveFileId")
values
  ($1, $2, $3)
on conflict ("userId", "assetId") do update
set
  "driveFileId" = "excluded"."driveFileId"
